# Generated by Django 6.1 on 2026-09-02 00:58

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='event title')),
                ('slug', models.SlugField(help_text='Auto-generated from title. Used in the event URL. Must be unique.', max_length=350, unique=True, verbose_name='URL slug')),
                ('short_description', models.TextField(help_text='Brief description shown on event cards and listing pages. Max 600 chars.', max_length=600, verbose_name='short description')),
                ('poster', models.ImageField(blank=True, help_text='Recommended: 16:9 ratio, min 1200px wide, JPG or PNG.', null=True, upload_to='events/posters/', verbose_name='event poster / cover image')),
                ('start_date', models.DateTimeField(verbose_name='start date & time')),
                ('end_date', models.DateTimeField(blank=True, help_text='Optional. For single-day events, leave blank.', null=True, verbose_name='end date & time')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='event status')),
                ('is_featured', models.BooleanField(default=False, help_text='Show this event in the Featured section on the homepage.', verbose_name='featured on homepage')),
                ('registration_link', models.URLField(blank=True, default='', help_text='External registration URL (e.g., Google Form). Leave blank to hide the Register button.', verbose_name='registration link')),
                ('registration_deadline', models.DateTimeField(blank=True, help_text='Optional. Informational only – does not auto-close the link.', null=True, verbose_name='registration deadline')),
                ('category', models.CharField(blank=True, default='', help_text='e.g., Workshop, Hackathon, Seminar, Competition, Webinar', max_length=100, verbose_name='category')),
                ('tags', models.CharField(blank=True, default='', help_text='Comma-separated tags for filtering. e.g., innovation, AI, startup', max_length=500, verbose_name='tags')),
                ('venue', models.CharField(blank=True, default='', help_text='Physical venue or "Online" or "Hybrid"', max_length=500, verbose_name='venue')),
                ('venue_link', models.URLField(blank=True, default='', help_text='Optional Google Maps or other map link.', verbose_name='venue map link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', help_text='Rich content for the event detail page. Use the editor to add text, images, tables, links, etc.', verbose_name='content')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last updated')),
            ],
            options={
                'verbose_name': 'Event Content',
                'verbose_name_plural': 'Event Contents',
            },
        ),
        migrations.CreateModel(
            name='EventGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Recommended: JPG or WebP, max 5MB.', upload_to='events/gallery/', verbose_name='image')),
                ('caption', models.CharField(blank=True, default='', max_length=300, verbose_name='caption')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
            ],
            options={
                'verbose_name': 'Event Gallery Image',
                'verbose_name_plural': 'Event Gallery Images',
                'ordering': ['event', 'order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EventReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', help_text='Write the event report here. Supports rich text, images, tables.', verbose_name='report content')),
                ('pdf_file', models.FileField(blank=True, help_text='Optional: Upload a PDF report.', null=True, upload_to='events/reports/', verbose_name='report PDF')),
                ('external_link', models.URLField(blank=True, default='', help_text='Optional: Link to report on Google Drive or elsewhere.', verbose_name='external report link')),
                ('is_published', models.BooleanField(default=False, help_text='Uncheck to hide the report from the public while editing.', verbose_name='published')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last updated')),
            ],
            options={
                'verbose_name': 'Event Report',
                'verbose_name_plural': 'Event Reports',
            },
        ),
        migrations.CreateModel(
            name='EventStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., "Registration Open", "Event Day", "Certificates Available"', max_length=200, verbose_name='stage name')),
                ('description', models.CharField(blank=True, default='', help_text='Optional brief description of this stage.', max_length=500, verbose_name='stage description')),
                ('stage_order', models.PositiveSmallIntegerField(default=0, help_text='Lower number = earlier stage. Stages are displayed left-to-right.', verbose_name='order')),
                ('start_date', models.DateField(blank=True, help_text='Informational only. Does not auto-trigger status changes.', null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('is_current', models.BooleanField(default=False, help_text='Mark this as the currently active stage. Only one stage should be current per event.', verbose_name='current stage')),
                ('is_completed', models.BooleanField(default=False, help_text='Mark this stage as completed (shown with a checkmark).', verbose_name='completed')),
            ],
            options={
                'verbose_name': 'Event Stage',
                'verbose_name_plural': 'Event Stages',
                'ordering': ['event', 'stage_order'],
            },
        ),
    ]
