# Generated by Django 6.1 on 2026-09-02 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='eventcontent',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='events.event', verbose_name='event'),
        ),
        migrations.AddField(
            model_name='eventgalleryimage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='events.event', verbose_name='event'),
        ),
        migrations.AddField(
            model_name='eventreport',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='events.event', verbose_name='event'),
        ),
        migrations.AddField(
            model_name='eventstage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='events.event', verbose_name='event'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', '-start_date'], name='events_even_status_489d0f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['slug'], name='events_even_slug_30eb0f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_featured'], name='events_even_is_feat_765082_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventstage',
            unique_together={('event', 'stage_order')},
        ),
    ]
