# Generated by Django 6.1 on 2026-09-02 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_label', models.CharField(help_text='e.g., "2025-2026" or "2024-25"', max_length=50, unique=True, verbose_name='year label')),
                ('is_current', models.BooleanField(default=False, help_text='Only one year should be marked as current.', verbose_name='current council year')),
                ('description', models.TextField(blank=True, default='', help_text='Optional notes about this council year.', verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Council Year',
                'verbose_name_plural': 'Council Years',
                'ordering': ['-year_label'],
            },
        ),
        migrations.CreateModel(
            name='CouncilMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='full name')),
                ('role', models.CharField(help_text='e.g., President, Vice President, Faculty Advisor, Secretary', max_length=200, verbose_name='role / position')),
                ('designation', models.CharField(blank=True, default='', help_text='For faculty: their academic designation. For students: branch and year.', max_length=300, verbose_name='designation / department')),
                ('member_type', models.CharField(choices=[('faculty', 'Faculty'), ('student', 'Student')], db_index=True, default='student', max_length=20, verbose_name='member type')),
                ('photo', models.ImageField(blank=True, help_text='Square photo recommended. Min 300x300px.', null=True, upload_to='council/photos/', verbose_name='profile photo')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email address')),
                ('linkedin_url', models.URLField(blank=True, default='', verbose_name='LinkedIn profile')),
                ('order_no', models.PositiveSmallIntegerField(default=0, help_text='Lower number = displayed first. Used to sort members on the page.', verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active in this council')),
                ('council_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='council.councilyear', verbose_name='council year')),
            ],
            options={
                'verbose_name': 'Council Member',
                'verbose_name_plural': 'Council Members',
                'ordering': ['council_year', 'member_type', 'order_no', 'name'],
            },
        ),
    ]
