# Generated by Django 6.1 on 2026-09-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/', verbose_name='image')),
                ('date', models.DateField(blank=True, help_text='Date of the achievement or award.', null=True, verbose_name='date')),
                ('category', models.CharField(choices=[('award', 'Award'), ('recognition', 'Recognition'), ('milestone', 'Milestone'), ('ranking', 'Ranking'), ('other', 'Other')], db_index=True, default='other', max_length=20, verbose_name='category')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured on homepage')),
                ('external_link', models.URLField(blank=True, default='', help_text='Optional link for more information about this achievement.', verbose_name='reference link')),
                ('order_no', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
