# Generated by Django 6.1 on 2026-09-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(db_index=True, help_text='Unique certificate identifier. e.g., IIC-IEM-2026-IDEA-001', max_length=200, unique=True, verbose_name='certificate ID')),
                ('recipient_name', models.CharField(help_text='Full name of the certificate recipient.', max_length=300, verbose_name='recipient name')),
                ('certificate_type', models.CharField(default='Participant', help_text='e.g., Participant, Winner, Runner-Up, Volunteer, Speaker, Organizer', max_length=200, verbose_name='certificate type')),
                ('issue_date', models.DateField(help_text='Date the certificate was issued.', verbose_name='issue date')),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('revoked', 'Revoked'), ('expired', 'Expired')], db_index=True, default='valid', max_length=20, verbose_name='status')),
                ('revocation_reason', models.TextField(blank=True, default='', help_text='Required when revoking a certificate. Not shown publicly.', verbose_name='revocation reason')),
                ('notes', models.TextField(blank=True, default='', help_text='Internal admin notes. Not visible to the public.', verbose_name='internal notes')),
                ('import_batch', models.CharField(blank=True, default='', help_text='Batch identifier for bulk imports. Helps track which upload this came from.', max_length=100, verbose_name='import batch ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issue_date', 'certificate_id'],
            },
        ),
        migrations.CreateModel(
            name='CertificateImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=100, unique=True, verbose_name='batch ID')),
                ('file_name', models.CharField(max_length=500, verbose_name='original file name')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='total rows')),
                ('imported_count', models.PositiveIntegerField(default=0, verbose_name='imported')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='skipped / duplicates')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='errors')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Completed')], default='in_progress', max_length=20, verbose_name='import status')),
                ('error_details', models.TextField(blank=True, default='', verbose_name='error details')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='imported at')),
            ],
            options={
                'verbose_name': 'Certificate Import Log',
                'verbose_name_plural': 'Certificate Import Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
