# Generated by Django 6.1 on 2026-09-02 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='event',
            field=models.ForeignKey(blank=True, help_text='The event this certificate is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='events.event', verbose_name='event'),
        ),
        migrations.AddField(
            model_name='certificateimportlog',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event', verbose_name='event'),
        ),
    ]
