# Generated by Django 6.1 on 2026-09-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='title')),
                ('content', models.TextField(help_text='The announcement text. Supports basic formatting.', verbose_name='content')),
                ('link', models.URLField(blank=True, default='', help_text='Optional: URL for a "Read More" or action button.', verbose_name='call-to-action link')),
                ('link_text', models.CharField(blank=True, default='Read More', help_text='Text for the link button, if a link is provided.', max_length=100, verbose_name='link button text')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent')], default='normal', max_length=20, verbose_name='priority')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this announcement without deleting it.', verbose_name='active / published')),
                ('show_on_home', models.BooleanField(default=True, help_text='Show this announcement in the homepage announcements section.', verbose_name='show on homepage')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional: Auto-hide this announcement after this date/time.', null=True, verbose_name='expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
