# Generated by Django 6.1 on 2026-09-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='IIC – IEM', max_length=200, verbose_name='site name')),
                ('tagline', models.CharField(blank=True, default="Institution's Innovation Council | IEM Kolkata", max_length=500, verbose_name='tagline')),
                ('logo', models.ImageField(blank=True, help_text='Recommended: PNG with transparent background, min 200px height.', null=True, upload_to='site/', verbose_name='logo')),
                ('favicon', models.ImageField(blank=True, help_text='Square image, 32x32 or 64x64 px.', null=True, upload_to='site/', verbose_name='favicon')),
                ('hero_tagline', models.CharField(blank=True, default='Fostering Innovation & Entrepreneurship', max_length=300, verbose_name='hero tagline')),
                ('hero_description', models.TextField(blank=True, default="The Institution's Innovation Council at IEM Kolkata works to promote a culture of innovation, creativity, and entrepreneurship among students.", verbose_name='hero description')),
                ('hero_background', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='hero background image')),
                ('about_iic', models.TextField(blank=True, default='', help_text='Rich text about IIC at national level.', verbose_name='about IIC')),
                ('about_iic_at_iem', models.TextField(blank=True, default='', help_text='Specific information about IIC at IEM Kolkata.', verbose_name='about IIC at IEM')),
                ('vision', models.TextField(blank=True, default='', verbose_name='vision')),
                ('mission', models.TextField(blank=True, default='', verbose_name='mission')),
                ('objectives', models.TextField(blank=True, default='', help_text='List the key objectives. Can use newlines.', verbose_name='objectives')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='contact email')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='contact phone')),
                ('contact_address', models.TextField(blank=True, default='', verbose_name='contact address')),
                ('facebook_url', models.URLField(blank=True, default='', verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, default='', verbose_name='Instagram URL')),
                ('twitter_url', models.URLField(blank=True, default='', verbose_name='Twitter / X URL')),
                ('linkedin_url', models.URLField(blank=True, default='', verbose_name='LinkedIn URL')),
                ('youtube_url', models.URLField(blank=True, default='', verbose_name='YouTube URL')),
                ('website_url', models.URLField(blank=True, default='', verbose_name='Official Website URL')),
                ('footer_text', models.TextField(blank=True, default='© IIC – IEM Kolkata. All Rights Reserved.', verbose_name='footer text')),
                ('footer_links_json', models.TextField(blank=True, default='', help_text='JSON array of {label, url} objects for footer quick links.', verbose_name='footer quick links (JSON)')),
                ('meta_description', models.TextField(blank=True, default="Official website of the Institution's Innovation Council (IIC) at IEM Kolkata.", max_length=300, verbose_name='default meta description')),
                ('meta_keywords', models.CharField(blank=True, default='IIC, IEM, innovation, council, Kolkata, entrepreneurship', max_length=500, verbose_name='meta keywords')),
                ('google_analytics_id', models.CharField(blank=True, default='', help_text='e.g., G-XXXXXXXXXX', max_length=50, verbose_name='Google Analytics ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last updated')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
