# Generated by Django 6.1 on 2026-09-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='president_designation',
            field=models.CharField(blank=True, default='President, IIC IEM & President, IEM UEM Group', max_length=300, verbose_name='president designation'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='president_image',
            field=models.ImageField(blank=True, help_text='Photo of President / Director.', null=True, upload_to='site/', verbose_name='president photo'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='president_message',
            field=models.TextField(blank=True, default="The IEM UEM Group has set sublime standards in addressing technical and managerial innovation. Our Institution's Innovation Council serves as a catalyst for student startups, research breakthroughs, and national-level entrepreneurship.", verbose_name='president message'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='president_name',
            field=models.CharField(blank=True, default='Prof. Dr. Satyajit Chakrabarti', max_length=200, verbose_name='president name'),
        ),
    ]
