# Generated by Django 6.1 on 2026-09-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_president_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='stat_1_label',
            field=models.CharField(blank=True, default='Innovation Workshops & Hackathons', max_length=150, verbose_name='stat 1 description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_1_number',
            field=models.CharField(blank=True, default='120+', help_text='e.g. "120+"', max_length=50, verbose_name='stat 1 number/value'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_2_label',
            field=models.CharField(blank=True, default='Student Startups Mentored', max_length=150, verbose_name='stat 2 description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_2_number',
            field=models.CharField(blank=True, default='45+', help_text='e.g. "45+"', max_length=50, verbose_name='stat 2 number/value'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_3_label',
            field=models.CharField(blank=True, default='Patents & Copyrights Filed', max_length=150, verbose_name='stat 3 description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_3_number',
            field=models.CharField(blank=True, default='30+', help_text='e.g. "30+"', max_length=50, verbose_name='stat 3 number/value'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_4_label',
            field=models.CharField(blank=True, default='Grant Exposure & Funding Support', max_length=150, verbose_name='stat 4 description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_4_number',
            field=models.CharField(blank=True, default='₹2.5 Cr+', help_text='e.g. "₹2.5 Cr+"', max_length=50, verbose_name='stat 4 number/value'),
        ),
    ]
