# Generated by Django 6.1 on 2026-09-02 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='album title')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('cover_image', models.ImageField(blank=True, help_text='Used as the album thumbnail on the gallery listing page.', null=True, upload_to='gallery/covers/', verbose_name='cover image')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('order_no', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'ordering': ['order_no', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='JPG or WebP recommended. Max 5MB.', upload_to='gallery/images/', verbose_name='image')),
                ('caption', models.CharField(blank=True, default='', max_length=400, verbose_name='caption')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.album', verbose_name='album')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['album', 'order', 'uploaded_at'],
            },
        ),
    ]
